### ISSUE TITLE
harness-runner does not properly kill java test app process

### ISSUE THREAD

**Issue by rspurgeon** [confluentinc/kafka-tutorials#157] opened 2019-10-03 15:08 UTC
When running the harness-runner, my java process will continue to run even after the harness-runner has stopped executing, leaving the java process to continue to run and print stdout to my terminal.  I'm required to find the process id and kill it manually in order to return the terminal to a usable state and properly cleanup the run.

running `make demo` from inside the `finding-distinct` tutorial code folder is how i've be able to reproduce this error at commit  https://github.com/confluentinc/kafka-tutorials/commit/3b6923e01a2c97b125b37a1a371ac6c32ea59763

**Comment by bbejeck** [comment] 2021-02-22 21:25
Triaging the bugs found in the issues.  I was unable to reproduce this error. Running the `make tutorial` command, the harness-runner executes as expected.  I'm closing this issue for now.

**Closed by bbejeck** 2021-02-22 21:25 UTC
Labels: bug
