### ISSUE TITLE
rendering issues / font 

### ISSUE THREAD

**Issue by gAmUssA** [confluentinc/kafka-tutorials#325] opened 2020-04-13 13:50 UTC
Font / text looks off

<img width="606" alt="image" src="https://user-images.githubusercontent.com/433085/79125274-e975b700-7d6b-11ea-8879-5ce1ab5b27e2.png">

A production version of KT website
Safari Version 13.1 (15609.1.20.111.8)

chrome version looks off as well  (but at least font is ok)

<img width="601" alt="image" src="https://user-images.githubusercontent.com/433085/79125433-2cd02580-7d6c-11ea-8898-4ea43518ea65.png">

**Comment by colinhicks** [comment] 2020-04-13 14:47
The rendering of `KAFKA TUTORIALS` in browsers which cannot use a local install of Roboto was addressed in https://github.com/confluentinc/kafka-tutorials/pull/326.

The navigation links are rendering as intended.
- The logo + Kafka Tutorials subdomain link matches the style of developer.confluent.io
- The Confluent Developer link at right is a normal hyperlink, matching the style of other company page headers.
- The Contribute link at right is styled as a button, matching its action orientation. This is similar to the `DOWNLOAD` button on other confluent.io pages.

**Closed by colinhicks** 2020-04-13 14:47 UTC
