### ISSUE TITLE
Topic Replica and Partition Count Manipulation

### ISSUE THREAD

**Issue by colinhicks** [confluentinc/kafka-tutorials#279] opened 2020-03-14 00:21 UTC
Change the properties of Kafka topics with KSQL by defining new streams with the desired properties of the new topic, populated by the streaming events of the original topic.

label: PARTITIONING

**Comment by ybyzek** [comment] 2020-07-21 02:10
Closing this GH issue because it is a duplicate of https://github.com/confluentinc/kafka-tutorials/issues/446

**Closed by ybyzek** 2020-07-21 02:10 UTC
Labels: cookbook, recipe
