### ISSUE TITLE
Fix typo in console-consumer-producer basic tutorial

### ISSUE THREAD

**Issue by rspurgeon** [confluentinc/kafka-tutorials#616] opened 2020-11-04 19:26 UTC
Currently, this tutorial lives in the mis-named: console-consumer-produer-basic

**Comment by ybyzek** [comment] 2020-11-04 19:32
@rspurgeon is this a dupe of https://github.com/confluentinc/kafka-tutorials/issues/471 ?

**Closed** 2020-11-04 19:36 UTC
Labels: duplicate
